language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: As/xLZGtnncU+JwRMI7Y1QkMJzkfJsMtfEWhGDRkCZ5bBK8klmQ7GGlqeTT1IARbIDQSEOVXhHWpK+7y7vZVq5ZeDgYxcAx6/nIkmuNJZiyxX3kvX7CzGeEhjSI2Etgnl8xh8WyBWqV+3wfISCyHOwWaD8iZ/gOUqe9G9KaNOzI=
